### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Kris6-km** [s-marian/DTSU666_CHINT_to_HUAWEI_translator#1]
Hello
At the beginning, I must say that I am a very beginner.
I try to compile the program but got this error every time.
Can you help me somehow?

FAILED: DTSU666H_translator.elf
cmd.exe /C "cd . && C:\Espressif\tools\xtensa-esp32-elf-clang\esp-14.0.0-20220415-x86_64-pc-windows-msvc\bin\xtensa-esp32-elf-g++.exe -mlongcalls -Wno-frame-address  @CMakeFiles\DTSU666H_translator.elf.rsp -o DTSU666H_translator.elf  && cd ."
c:/espressif/tools/xtensa-esp32-elf-clang/esp-14.0.0-20220415-x86_64-pc-windows-msvc/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/freertos/libfreertos.a(port_common.c.obj):(.literal.main_task+0x14): undefined reference to `app_main'
c:/espressif/tools/xtensa-esp32-elf-clang/esp-14.0.0-20220415-x86_64-pc-windows-msvc/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/freertos/libfreertos.a(port_common.c.obj): in function `main_task':
C:/Users/kryst/esp/esp-idf/components/freertos/port/port_common.c:125: undefined reference to `app_main'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by s-marian** [comment]
Hi @Kris6-km 

This looks like either
a) you did not clone the repository using --recurse-submodules. Can you check that components/arduino exists on your side? Added information in README.md.
b) you modified somehow the sdkconfig file included in the repository

I also need to mention that i only compiled this on Linux, not Windows.
